name: bb3_helper
description: "Companion app for Blood Bowl 3"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  bloodbowl3_dart:
    git: git@github.com:mjbader/bloodbowl3_dart.git
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  fluent_ui: ^4.13.0
  flutter_acrylic: ^1.0.0+2
  provider: ^6.0.5
  go_router: ^16.0.0
  window_manager: ^0.5.0
  clipboard: ^0.1.3
  system_theme: ^3.1.2
  url_strategy: ^0.3.0
  url_launcher: ^6.1.7
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  math_expressions: ^2.7.0

flutter:
  uses-material-design: true

flutter_icons:
  android: false
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "202020"
    theme_color: "0175C2"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"